version: '3.8'

services:

  db:
    container_name: postgresSchool
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rhschool
    ports:
      - "5433:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin4School
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: msregistration@admin.com
      PGADMIN_DEFAULT_PASSWORD: msregistration
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge